name: Build and Deploy

on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with: 
          node-version: "14.x"

      - name: Install dependencies
        run: npm install

  test:
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - name: Run test
        run: npm test
  
  deploy:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Run test
        run: npm test
