name: Test - Build - Deploy

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  test-node-js:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with: 
          node-version: "16.x"

      - name: Run test
        working-directory: node-js
        run: |
          npm install
          npm install express 
          npm install jest supertest
          npm test
  
  test-go:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.14'
          check-latest: true

      - run: go version
  
  # build:
  #   runs-on: ubuntu-latest
  #   needs: [test-node-js], [test-go]
  #   steps:
  #     - name: Run test
  #       run: npm test ./node-js
