name: Build and Deploy

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with: 
          node-version: "16.x"

  test-node-js:
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - name: Run test
        working-directory: node-js
        run: |
          ls
          npm install
          npm test
  
  # test-go:
  #   runs-on: ubuntu-latest
  #   needs: [setup]
  #   steps:
  #     - name: Run test
  #       run: npm test ./node-js
  
  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: [test]
  #   steps:
  #     - name: Run test
  #       run: npm test ./node-js
